### ISSUE TITLE
Since Android 15, tapping single note widget sometimes creates "New note" instead of opening the linked note

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notes-android#2790]
Please make a clear and concise description of what the bug is.

## Steps to reproduce
1. Use the single note widget
2. Tap on it

### Expected behaviour
It always opens the linked note.

### Actual behaviour
Since Android 15, it sometimes (not sure when) creates a "New note" and opens that.
In Android 14 already it sometimes opened the list of notes instead of the linked note, but this new, also erroneous behavior is a bit worse and more annoying. ;)

## Server
Please complete the following information.

- Notes app version: 4.11.0
- Nextcloud version: 31.0.7

**Comment by af7567** [comment]
Just tested the current play store versions of Notes and Nextcloud on Android 12 and the single note widget works fine.
I have also previously used Notes v4.3.1 and earlier on Android 15 and 16 with no widget problems.
With the release of v4.4.0 the widget opens a new note every time, so it seems to be a combination of Android 15+ and the code being converted from Java to Kotlin.

Similar to https://github.com/nextcloud/notes-android/issues/2748

**Comment by af7567** [comment]
I was wrong about the Java to Kotlin thing, I tried replacing the .kt with the original .java widget and it made no difference. 
After checking out v4.3.1 and compiling it, everything works properly again on Android 16. It is also OK after changing the target sdk to 35 and updating the dependencies to match the current main branch.
So something else in the notes app code which changed between 4.3.1 and 4.4.0 is causing it (maybe :) ).

**Comment by af7567** [comment]
It seems this is the change which has prevented the note id being kept in the extras: 
https://github.com/nextcloud/notes-android/commit/f0c7da7cd61b686950aa6225e7411e194a02dff2

Commenting those lines out fixes the single note and note list widgets for me on Android 16. I don't get any exception thrown about implicit intent but I am unsure whether that problem would apply to these widgets.

https://developer.android.com/reference/android/app/PendingIntent.html#FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT

**Comment by tobiasKaminsky** [comment]
Hint: Happens only if app was not opened before.

Another bug: when re-open the app, then previous view is opened, but not the note connected to the widget.

**Comment by ZetaTom** [comment]
Issue for Android 14: #2261

**Comment by eve-nisse** [comment]
Confirming issue as already described, except it always happens.

**Comment by af7567** [comment]
My workaround of reversing the PendingIntent flags change no longer works since the Android 16 September security update.

**Comment by Bitsauger** [comment]
I can confirm and the same as described in #2147 - im now on Android 15 with Notes Android App 4.5.0 and 4.12.3 on Nextcloud.

**Comment by Phoenix616** [comment]
Also happens for a while now with the list widget for me (Android 14, Notes 4.5.0), not only the single note widget.

**Comment by cathodoluminescence** [comment]
Same here. It is really annyoing. I remember that this occured a year ago or so once before, but was fixed somehow.

Android 14
Notes (Client App) 4.5.1 (F-Droid)
NC Client  3.34 (F-Droid)
Notes (Server App) 4.12.3 on [Nextcloud Hub 10 (31.0.8)

**Comment by BloodyIron** [comment]
This was identified in #2748 in addition to other regressions as far back as in... JULY.

**Comment by jancborchardt** [comment]
Hi @BloodyIron, it is being worked on, and disparaging comments won’t make it go faster. Please be considerate as outlined in our [code of conduct](https://nextcloud.com/contribute/code-of-conduct/). Thank you ❤️

**Comment by BloodyIron** [comment]
> Hi [@BloodyIron](https://github.com/BloodyIron), it is being worked on, and disparaging comments won’t make it go faster. Please be considerate as outlined in our [code of conduct](https://nextcloud.com/contribute/code-of-conduct/). Thank you ❤️

THANKS but quite frankly we've had radio silence for months (from the devs, so far as I could tell). So it would have been appreciated to be informed it was being worked on... well.. any time earlier than this. Considering I paid for this app and it has had a rather breaking regression without being rolled back, I have reasonable grounds to be upset.

I just re-reviewed what I said in this and the other thread and at no way does what I say violate the code of conduct. Being frustrated is not a policy or code violation.

**Comment by alperozturk96** [comment]
Hey.

The issue fixed via: https://github.com/nextcloud/notes-android/pull/2887.

We will release a new version. Thank you.

**Comment by BloodyIron** [comment]
> Hey.
> 
> The issue fixed via: [#2887](https://github.com/nextcloud/notes-android/pull/2887).
> 
> We will release a new version. Thank you.

Yay thanks! :D

Does this also solve the blue bar thing?

**Comment by g-work** [comment]
Both problems (blue bars and new note instead of opening) still occure. Android 16 on Pixel 9, newest Nextcloud and Notes app.

**Comment by BloodyIron** [comment]
yeah I'm still having both problems... I don't think this is getting taken seriously at all :/ frustrating considering I paid for this app.

**Comment by alperozturk96** [comment]
The widget content color issue is fixed with this PR: https://github.com/nextcloud/notes-android/pull/3026

You can test [4.6.0 RC1](https://github.com/nextcloud/notes-android/releases/tag/rc-4.6.0-01) and share your feedback with us.
